trigger:
- main

pool:
  vmImage: ubuntu-latest

stages :
 
  - stage: deploy_agent_resources
    jobs:
      - job: "BicepConfigure"
        steps:
  
          - task: Bash@3
            displayName: 'Install & run Bicep'
            inputs:
              targetType: inline
              script: |
                # Fetch the latest Bicep CLI binary
                curl -Lo bicep.bin https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
                # Mark it as executable
                chmod +x ./bicep.bin
                # Add bicep to your PATH (requires admin)
                sudo mv ./bicep.bin /usr/local/bin/bicep
                # Verify you can now access the 'bicep' command
                bicep --help
                # Done!
                bicep build $(System.DefaultWorkingDirectory)/bicep/main.bicep -adminPassword $(ADMINPASSWORD) -adminUsername $(ADMINUSERNAME) -instanceCount $(INSTANCECOUNT) -vmssName $(VMSSNAME)
 
          - task: AzureCLI@2
            displayName: 'Deploy generated ARM'
            inputs:
              azureSubscription: 'Internal Consumption tostille(7d5e75b2-656e-4a96-b12f-24e2e79a8279)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                #!/bin/bash
                az group create -l northeurope -n bicep-rg 
                az deployment group create -f $(System.DefaultWorkingDirectory)/bicep/main.json -g bicep-rg
              addSpnToEnvironment: true


